backend:
  name: github
  repo: jagarnica/personalsite
  site_domain: www.jesusgarnica.com
  squash_merges: true # Done to prevent creating multiple pull requests for the same article
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
site_url: https://www.jesusgarnica.com/
publish_mode: editorial_workflow

collections:
  - name: "PersonalSite"
    label: "Post"
    folder: "content/blog"
    create: true
    media_folder: ""
    public_folder: ""
    slug: "index"
    path: "{{year}}-{{month}}-{{day}}/{{title}}"
    preview_path: "blog/{{year}}-{{month}}-{{day}}/{{title}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          picker_utc: true,
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Published", name: "published", widget: "boolean", false }
